limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

server {
    listen 80;
    server_name localhost;

    # Redirigir /api/auth al backend (con rate limit en login)
    location /api/auth/ {
        limit_req zone=login burst=2 nodelay;
        rewrite ^/api(/.*) $1 break;
        proxy_pass http://sgp_api_backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redirigir /api/uploads a MinIO (object storage)
    location /api/uploads/ {
        proxy_pass http://minio:9000/sgp-uploads/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirigir /api al backend de NestJS
    location /api/ {
        rewrite ^/api(/.*) $1 break;
        proxy_pass http://sgp_api_backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redirigir todo lo demás al frontend de Vite
    location / {
        proxy_pass http://sgp_frontend_dev:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
